# Generated by Django 3.1.1 on 2021-01-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Summoner',
        ),
    ]
