# Generated by Django 3.1.1 on 2021-01-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210121_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='Summoner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.summoner'),
        ),
    ]
