# Generated by Django 3.1.1 on 2021-01-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210121_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['-Num_played']},
        ),
    ]
