# Generated by Django 3.1.1 on 2021-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210121_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_id', models.CharField(db_index=True, max_length=200)),
                ('Duration', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
