# Generated by Django 3.1.1 on 2021-01-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20210121_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Champion_link',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
