# Generated by Django 3.1.1 on 2021-01-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20210121_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Perk0',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Perk1',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Perk2',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Perk3',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Perk4',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Perk5',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
