# Generated by Django 3.1.1 on 2021-01-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20210121_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='Duration',
            new_name='Min_played',
        ),
        migrations.AddField(
            model_name='match',
            name='Sec_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
