# Generated by Django 3.1.1 on 2021-01-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_summoner_most_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Queue_type',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
