# Generated by Django 3.1.1 on 2021-01-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_champion_queue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='LargestMultiKill',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
