# Generated by Django 3.1.1 on 2021-01-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20210123_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='Most_recent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
