# Generated by Django 3.1.1 on 2021-01-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_auto_20210123_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Match_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
