# Generated by Django 3.1.1 on 2021-01-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_auto_20210125_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='Assists',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Champ_level',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Champion',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Champion_link',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Deaths',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Item0',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Item1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Item2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Item3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Item4',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Item5',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Kills',
        ),
        migrations.RemoveField(
            model_name='match',
            name='LargestMultiKill',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Perk0',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Perk1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Perk2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Perk3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Perk4',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Perk5',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Spell1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Spell2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Vision_ward',
        ),
    ]
