# Generated by Django 3.1.1 on 2021-01-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_match_champion_kda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_champion',
            old_name='KDA',
            new_name='Kda',
        ),
    ]
