# Generated by Django 3.1.1 on 2021-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0034_summoner_searched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='Searched',
            field=models.CharField(db_index=True, default='False', max_length=200),
        ),
    ]
