"""
Django settings for RiotAPI project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from riotwatcher import LolWatcher, ApiError
from pathlib import Path
from collections import defaultdict
import os
import pymysql
import requests
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g@6l7v&oxjo_vpwg&_s20*9b0jj5096o%^^#0$jex9yb118p!*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# golbal variables
API_KEY = ''
WATCHER = LolWatcher(API_KEY)
MY_REGION = 'na1'

# check league's latest version
LATEST = WATCHER.data_dragon.versions_for_region(MY_REGION)['n']['champion']

# Lets get some champions static information
STATIC_CHAMP_LIST = WATCHER.data_dragon.champions(LATEST, False, 'en_US')
CHAMP_DICT = {}
for key in STATIC_CHAMP_LIST['data']:
    row = STATIC_CHAMP_LIST['data'][key]
    CHAMP_DICT[row['key']] = row['id']
# Getting Item Info
req1 = requests.get(
    'http://ddragon.leagueoflegends.com/cdn/11.1.1/data/en_US/item.json')
ITEM_DICT = req1.json()['data']

# Getting Summoner Spell Info
req2 = requests.get(
    'http://ddragon.leagueoflegends.com/cdn/11.1.1/data/en_US/summoner.json')
SS_DICT = req1.json()['data']

req3 = requests.get(
    'http://ddragon.leagueoflegends.com/cdn/11.1.1/data/en_US/runesReforged.json')
temp = req3.json()
PERK_DICT = {}
for major in temp:
    runes = major['slots']
    for rune in runes:
        list = rune["runes"]
        for item in list:
            PERK_DICT[item["id"]] = item["key"]


SUMMONER_DICT = {}
SUMMONER_DICT[1] = "Cleanse"
SUMMONER_DICT[3] = "Exhaust"
SUMMONER_DICT[4] = "Flash"
SUMMONER_DICT[6] = "Ghost"
SUMMONER_DICT[7] = "Heal"
SUMMONER_DICT[11] = "Smite"
SUMMONER_DICT[12] = "Teleport"
SUMMONER_DICT[13] = "Clarity"
SUMMONER_DICT[14] = "Ignite"
SUMMONER_DICT[21] = "Barrier"

ROLE_DICT = defaultdict(lambda: 'NONE')
ROLE_DICT[('DUO_CARRY', 'BOTTOM')] = 'ADC'
ROLE_DICT[('DUO_SUPPORT', 'NONE')] = 'SUPPORT'
ROLE_DICT[('SOLO', 'TOP')] = 'TOP'
ROLE_DICT[('NONE', 'JUNGLE')] = 'JUNGLE'
ROLE_DICT[('SOLO', 'BOTTOM')] = 'ADC'

POSITION = defaultdict(lambda: "BUG")
POSITION[("MID", "SOLO")] = "MID"
POSITION[("TOP", "SOLO")] = "TOP"
POSITION[("JUNGLE", "NONE")] = "JUN"
POSITION[("BOTTOM", "DUO_CARRY")] = "ADC"
POSITION[("BOTTOM", "DUO_SUPPORT")] = "SUP"
TIME_SHIFTS = {
    "oc1": -46800,
    "jp1": -43200,
    "kr": -39600,
    "ru": -28800,
    "eun1": -21600,
    "tr1": -18000,
    "euw1": -10800,
    "br1": -3600,
    "la2": 0,
    "la1": 7200,
    "na1": 10800,
    "ph": 43200,
    "id1": 43200,
    "vn": 46800,
    "sg": 50400,
    "th": 54000,
    "tw": 57600,
}

PATCHES = {
    "11": 1609920000,
    "10": 1578477600,
    "9": 1547020800,
    "8": 1515571200,
    "7": 1484121600,
}
CHAMPION_TO_ROLE = {}
CHAMPION_TO_ROLE['Aatrox'] = "TOP"
CHAMPION_TO_ROLE['Ahri'] = "MID"
CHAMPION_TO_ROLE['Akali'] = "MID"
CHAMPION_TO_ROLE['Alistar'] = "SUP"
CHAMPION_TO_ROLE['Amumu'] = "JUN"
CHAMPION_TO_ROLE['Anivia'] = "MID"
CHAMPION_TO_ROLE['Annie'] = "MID"
CHAMPION_TO_ROLE['Aphelios'] = "ADC"
CHAMPION_TO_ROLE['Ashe'] = "ADC"
CHAMPION_TO_ROLE['AurelionSol'] = "MID"
CHAMPION_TO_ROLE['Azir'] = "MID"
CHAMPION_TO_ROLE['Bard'] = "SUP"
CHAMPION_TO_ROLE['Blitzcrank'] = "SUP"
CHAMPION_TO_ROLE['Brand'] = "SUP"
CHAMPION_TO_ROLE['Braum'] = "SUP"
CHAMPION_TO_ROLE['Caitlyn'] = "ADC"
CHAMPION_TO_ROLE['Camille'] = "TOP"
CHAMPION_TO_ROLE['Cassiopeia'] = "MID"
CHAMPION_TO_ROLE['Chogath'] = "TOP"
CHAMPION_TO_ROLE['Corki'] = "MID"
CHAMPION_TO_ROLE['Darius'] = "TOP"
CHAMPION_TO_ROLE['Diana'] = "MID"
CHAMPION_TO_ROLE['Draven'] = "ADC"
CHAMPION_TO_ROLE['DrMundo'] = "TOP"
CHAMPION_TO_ROLE['Ekko'] = "JUN"
CHAMPION_TO_ROLE['Elise'] = "JUN"
CHAMPION_TO_ROLE['Evelynn'] = "JUN"
CHAMPION_TO_ROLE['Ezreal'] = 'ADC'
CHAMPION_TO_ROLE['Fiddlesticks'] = "JUN"
CHAMPION_TO_ROLE['Fiora'] = "TOP"
CHAMPION_TO_ROLE['Fizz'] = "MID"
CHAMPION_TO_ROLE['Galio'] = "MID"
CHAMPION_TO_ROLE['Gangplank'] = "TOP"
CHAMPION_TO_ROLE['Garen'] = "TOP"
CHAMPION_TO_ROLE['Gnar'] = "TOP"
CHAMPION_TO_ROLE['Gragas'] = "TOP"
CHAMPION_TO_ROLE['Graves'] = "JUN"
CHAMPION_TO_ROLE['Hecarim'] = "JUN"
CHAMPION_TO_ROLE['Heimerdinger'] = "TOP"
CHAMPION_TO_ROLE['Illaoi'] = "TOP"
CHAMPION_TO_ROLE['Irelia'] = "TOP"
CHAMPION_TO_ROLE['Ivern'] = "JUN"
CHAMPION_TO_ROLE['Janna'] = "SUP"
CHAMPION_TO_ROLE['JarvanIV'] = "JUN"
CHAMPION_TO_ROLE['Jax'] = "TOP"
CHAMPION_TO_ROLE['Jayce'] = "TOP"
CHAMPION_TO_ROLE['Jhin'] = "ADC"
CHAMPION_TO_ROLE['Jinx'] = "ADC"
CHAMPION_TO_ROLE['Kaisa'] = "ADC"
CHAMPION_TO_ROLE['Kalista'] = "ADC"
CHAMPION_TO_ROLE['Karma'] = "SUP"
CHAMPION_TO_ROLE['Karthus'] = "JUN"
CHAMPION_TO_ROLE['Kassadin'] = "MID"
CHAMPION_TO_ROLE['Katarina'] = "MID"
CHAMPION_TO_ROLE['Kayle'] = "TOP"
CHAMPION_TO_ROLE['Kayn'] = "JUN"
CHAMPION_TO_ROLE['Kennen'] = "TOP"
CHAMPION_TO_ROLE['Khazix'] = "JUN"
CHAMPION_TO_ROLE['Kindred'] = "JUN"
CHAMPION_TO_ROLE['Kled'] = "TOP"
CHAMPION_TO_ROLE['KogMaw'] = "ADC"
CHAMPION_TO_ROLE['Leblanc'] = "MID"
CHAMPION_TO_ROLE['LeeSin'] = "JUN"
CHAMPION_TO_ROLE['Leona'] = "SUP"
CHAMPION_TO_ROLE['Lillia'] = "JUN"
CHAMPION_TO_ROLE['Lissandra'] = "MID"
CHAMPION_TO_ROLE['Lucian'] = "BOT"
CHAMPION_TO_ROLE['Lulu'] = "SUP"
CHAMPION_TO_ROLE['Lux'] = "SUP"
CHAMPION_TO_ROLE['Malphite'] = "TOP"
CHAMPION_TO_ROLE['Malzahar'] = "MID"
CHAMPION_TO_ROLE['Maokai'] = "SUP"
CHAMPION_TO_ROLE['MasterYi'] = "JUN"
CHAMPION_TO_ROLE['MissFortune'] = "ADC"
CHAMPION_TO_ROLE['MonkeyKing'] = "TOP"
CHAMPION_TO_ROLE['Mordekaiser'] = "TOP"
CHAMPION_TO_ROLE['Morgana'] = "SUP"
CHAMPION_TO_ROLE['Nami'] = "SUP"
CHAMPION_TO_ROLE['Nasus'] = "TOP"
CHAMPION_TO_ROLE['Nautilus'] = "SUP"
CHAMPION_TO_ROLE['Neeko'] = "MID"
CHAMPION_TO_ROLE['Nidalee'] = "JUN"
CHAMPION_TO_ROLE['Nocturne'] = "JUN"
CHAMPION_TO_ROLE['Nunu'] = "JUN"
CHAMPION_TO_ROLE['Olaf'] = "JUN"
CHAMPION_TO_ROLE['Orianna'] = "MID"
CHAMPION_TO_ROLE['Ornn'] = "TOP"
CHAMPION_TO_ROLE['Pantheon'] = "SUP"
CHAMPION_TO_ROLE['Poppy'] = "TOP"
CHAMPION_TO_ROLE['Pyke'] = "SUP"
CHAMPION_TO_ROLE['Qiyana'] = "MID"
CHAMPION_TO_ROLE['Quinn'] = "TOP"
CHAMPION_TO_ROLE['Rakan'] = "SUP"
CHAMPION_TO_ROLE['Rammus'] = "JUN"
CHAMPION_TO_ROLE['RekSai'] = "JUN"
CHAMPION_TO_ROLE['Rell'] = "SUP"
CHAMPION_TO_ROLE['Renekton'] = "TOP"
CHAMPION_TO_ROLE['Rengar'] = "TOP"
CHAMPION_TO_ROLE['Riven'] = "TOP"
CHAMPION_TO_ROLE['Rumble'] = "TOP"
CHAMPION_TO_ROLE['Ryze'] = "MID"
CHAMPION_TO_ROLE['Samira'] = "ADC"
CHAMPION_TO_ROLE['Sejuani'] = "JUN"
CHAMPION_TO_ROLE['Senna'] = "SUP"
CHAMPION_TO_ROLE['Seraphine'] = "SUP"
CHAMPION_TO_ROLE['Sett'] = "TOP"
CHAMPION_TO_ROLE['Shaco'] = "SUP"
CHAMPION_TO_ROLE['Shen'] = "TOP"
CHAMPION_TO_ROLE['Shyvana'] = "JUN"
CHAMPION_TO_ROLE['Singed'] = "TOP"
CHAMPION_TO_ROLE['Sion'] = "TOP"
CHAMPION_TO_ROLE['Sivir'] = "ADC"
CHAMPION_TO_ROLE['Skarner'] = "JUN"
CHAMPION_TO_ROLE['Sona'] = "SUP"
CHAMPION_TO_ROLE['Soraka'] = "SUP"
CHAMPION_TO_ROLE['Swain'] = "SUP"
CHAMPION_TO_ROLE['Sylas'] = "MID"
CHAMPION_TO_ROLE['Syndra'] = "MID"
CHAMPION_TO_ROLE['TahmKench'] = "SUP"
CHAMPION_TO_ROLE['Taliyah'] = "JUN"
CHAMPION_TO_ROLE['Talon'] = "MID"
CHAMPION_TO_ROLE['Taric'] = "SUP"
CHAMPION_TO_ROLE['Teemo'] = "TOP"
CHAMPION_TO_ROLE['Thresh'] = "SUP"
CHAMPION_TO_ROLE['Tristana'] = "ADC"
CHAMPION_TO_ROLE['Trundle'] = "JG"
CHAMPION_TO_ROLE['Tryndamere'] = "TOP"
CHAMPION_TO_ROLE['TwistedFate'] = "MID"
CHAMPION_TO_ROLE['Twitch'] = "ADC"
CHAMPION_TO_ROLE['Udyr'] = "JUN"
CHAMPION_TO_ROLE['Urgot'] = "TOP"
CHAMPION_TO_ROLE['Varus'] = "ADC"
CHAMPION_TO_ROLE['Vayne'] = "ADC"
CHAMPION_TO_ROLE['Veigar'] = "MID"
CHAMPION_TO_ROLE['Velkoz'] = "SUP"
CHAMPION_TO_ROLE['Vi'] = "JUN"
CHAMPION_TO_ROLE['Viktor'] = "MID"
CHAMPION_TO_ROLE['Vladimir'] = "MID"
CHAMPION_TO_ROLE['Volibear'] = "TOP"
CHAMPION_TO_ROLE['Warwick'] = "JUN"
CHAMPION_TO_ROLE['Xayah'] = "ADC"
CHAMPION_TO_ROLE['Xerath'] = "SUP"
CHAMPION_TO_ROLE['XinZhao'] = "JUN"
CHAMPION_TO_ROLE['Yasuo'] = "MID"
CHAMPION_TO_ROLE['Yone'] = "MID"
CHAMPION_TO_ROLE['Yorick'] = "TOP"
CHAMPION_TO_ROLE['Yuumi'] = "SUP"
CHAMPION_TO_ROLE['Zac'] = "JUN"
CHAMPION_TO_ROLE['Zed'] = "MID"
CHAMPION_TO_ROLE['Ziggs'] = "MID"
CHAMPION_TO_ROLE['Zilean'] = "SUP"
CHAMPION_TO_ROLE['Zoe'] = "MID"
CHAMPION_TO_ROLE['Zyra'] = "SUP"
CHAMPION_TO_ROLE['Viego'] = "JUG"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'search',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RiotAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RiotAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
pymysql.version_info = (1, 4, 2, "final", 0)
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'riot-api.cjke3gda9ifw.us-west-1.rds.amazonaws.com',
        'NAME': 'RIOTAPI',
        'USER': 'admin',
        'PASSWORD': 'Qesu823892-',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
AWS_ACCESS_KEY_ID = 'AKIAQE4DB3YWSVMD6L7B'
AWS_SECRET_ACCESS_KEY = ''
AWS_REGION = 'us-west-1'
AWS_STORAGE_BUCKET_NAME = 'riotapi-static'
AWS_S3_CUSTOM_DOMAIN = f's3.{AWS_REGION}.amazonaws.com/{AWS_STORAGE_BUCKET_NAME}'
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = 'public-read'
AWS_LOCATION = ''
STATIC_URL = f'http://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

DEFAULT_FILE_STORAGE = '.s3media.MediaStorage'
