# Generated by Django 3.1.1 on 2021-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=200)),
                ('Img_link', models.CharField(db_index=True, max_length=200)),
                ('Num_played', models.PositiveIntegerField(default=0)),
                ('Num_won', models.PositiveIntegerField(default=0)),
                ('Kills', models.PositiveIntegerField(default=0)),
                ('Assists', models.PositiveIntegerField(default=0)),
                ('Deaths', models.PositiveIntegerField(default=0)),
                ('CS', models.PositiveIntegerField(default=0)),
                ('Mins_played', models.PositiveIntegerField(default=0)),
                ('Damage_dealt', models.PositiveIntegerField(default=0)),
                ('Gold', models.PositiveIntegerField(default=0)),
                ('KDA', models.PositiveIntegerField(default=0)),
                ('Kill_pg', models.PositiveIntegerField(default=0)),
                ('Death_pg', models.PositiveIntegerField(default=0)),
                ('Assist_pg', models.PositiveIntegerField(default=0)),
                ('Winrate', models.PositiveIntegerField(default=0)),
                ('Dpm', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
