# Generated by Django 3.1.1 on 2021-01-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_champion_summoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='Adc_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summoner',
            name='Jun_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summoner',
            name='Mid_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summoner',
            name='Num_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summoner',
            name='Sup_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summoner',
            name='Top_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
