# Generated by Django 3.1.1 on 2021-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_match_champion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Item0',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Item1',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Item2',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Item3',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Item4',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Item5',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
