# Generated by Django 3.1.1 on 2021-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20210122_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='Most_recent',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
