# Generated by Django 3.1.1 on 2021-01-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20210125_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='Summoner',
        ),
        migrations.AddField(
            model_name='match',
            name='Summoners',
            field=models.ManyToManyField(to='search.Summoner'),
        ),
        migrations.CreateModel(
            name='Match_Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_id', models.PositiveIntegerField(default=0)),
                ('Min_played', models.PositiveIntegerField(default=0)),
                ('Sec_played', models.PositiveIntegerField(default=0)),
                ('Queue_type', models.CharField(db_index=True, max_length=200, null=True)),
                ('Champion', models.CharField(db_index=True, max_length=200, null=True)),
                ('Champion_link', models.CharField(db_index=True, max_length=200, null=True)),
                ('Spell1', models.CharField(db_index=True, max_length=200, null=True)),
                ('Spell2', models.CharField(db_index=True, max_length=200, null=True)),
                ('Item0', models.CharField(db_index=True, max_length=200, null=True)),
                ('Item1', models.CharField(db_index=True, max_length=200, null=True)),
                ('Item2', models.CharField(db_index=True, max_length=200, null=True)),
                ('Item3', models.CharField(db_index=True, max_length=200, null=True)),
                ('Item4', models.CharField(db_index=True, max_length=200, null=True)),
                ('Item5', models.CharField(db_index=True, max_length=200, null=True)),
                ('Perk0', models.CharField(db_index=True, max_length=200, null=True)),
                ('Perk1', models.CharField(db_index=True, max_length=200, null=True)),
                ('Perk2', models.CharField(db_index=True, max_length=200, null=True)),
                ('Perk3', models.CharField(db_index=True, max_length=200, null=True)),
                ('Perk4', models.CharField(db_index=True, max_length=200, null=True)),
                ('Perk5', models.CharField(db_index=True, max_length=200, null=True)),
                ('Kills', models.PositiveIntegerField(default=0)),
                ('Deaths', models.PositiveIntegerField(default=0)),
                ('Assists', models.PositiveIntegerField(default=0)),
                ('LargestMultiKill', models.CharField(db_index=True, max_length=200, null=True)),
                ('Champ_level', models.PositiveIntegerField(default=0)),
                ('Vision_ward', models.PositiveIntegerField(default=0)),
                ('Summoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.summoner')),
            ],
        ),
    ]
