# Generated by Django 3.1.1 on 2021-01-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20210125_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Summoner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.summoner'),
        ),
        migrations.AlterField(
            model_name='match',
            name='Summoners',
            field=models.ManyToManyField(related_name='summoner', to='search.Summoner'),
        ),
    ]
