# Generated by Django 3.1.1 on 2021-01-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_champion',
            name='KDA',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
