# Generated by Django 3.1.1 on 2021-01-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_auto_20210126_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_champion',
            name='Win',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
