# Generated by Django 3.1.1 on 2021-01-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_match_champion_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_champion',
            name='Position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
