# Generated by Django 3.1.1 on 2021-01-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_auto_20210126_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_champion',
            name='Role',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
