# Generated by Django 3.1.1 on 2021-01-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_match_champion_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_champion',
            name='Kda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
