# Generated by Django 3.1.1 on 2021-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_auto_20210126_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_champion',
            name='Item6',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
