# Generated by Django 3.1.1 on 2021-01-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0035_auto_20210126_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='Gpm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
