# Generated by Django 3.1.1 on 2021-01-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0036_champion_gpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_champion',
            name='Summoner_name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
