# Generated by Django 3.1.1 on 2021-01-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_match_champion_summoner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_champion',
            name='Damage_dealt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
